language: go

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.21.0

script:
  - golangci-lint run --enable-all --disable=gochecknoinits,gochecknoglobals,scopelint
  - make test
